name: Split releases

on:
  release:
    types: ['published']

concurrency:
  group: split

env:
  GH_TOKEN: ${{ secrets.SPLITTER_ACCESS_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: Serializer, repo: serializer }
          - { namespace: PHPStan, repo: phpstan-extension }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          split_sha=`git subtree split --prefix=src/${{ matrix.package.namespace }}`
          repo_url="https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/prototype-php/${{ matrix.package.repo }}.git"
          if [ -z $(git ls-remote --tags "$repo_url" | grep "$split_sha") ]; then \
            gh release create ${{ github.ref_name }} \
              --repo prototype-php/${{ matrix.package.repo }} \
              --target "$split_sha" \
              --generate-notes \
              --notes '[See release information in Prototype monorepo](https://github.com/prototype-php/prototype/releases/tag/${{ github.ref_name }}).'; \
          fi