name: Split commits

on:
  push:
    branches: ['*.x']

concurrency:
  group: split

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: Serializer, repo: serializer }
          - { namespace: PHPStan, repo: phpstan-extension }
          - { namespace: Byte, repo: byte-buffer }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          repo_url="https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/prototype-php/${{ matrix.package.repo }}.git"
          git subtree push --prefix src/${{ matrix.package.namespace }} "$repo_url" ${{ github.ref_name }}